### ISSUE TITLE
CompactRaidFrame4:Show() error when in dungeon or raid (only one time per dungeon)

### ISSUE THREAD

**Issue by rbpaiett** [Thumbkin/MissingTradeSkillsList_TBC#10] opened 2021-06-08 23:15 UTC
So I get this error at random times in a dungeon but only one time per dungeon:

1x [ADDON_ACTION_BLOCKED] AddOn 'MissingTradeSkillsList_TBC' tried to call the protected function 'CompactRaidFrame4:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\CompactUnitFrame.lua"]:359: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML\CompactUnitFrame.lua"]:292: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML\CompactUnitFrame.lua"]:125: in function <FrameXML\CompactUnitFrame.lua:53>

I can't imagine how your addon is involved but it keeps coming up.
This would be hard to duplicate isolated since I don't raid or do dungeons without addons very well :(

It appears to happen when you're in a dungeon or your group is in a dungeon and the group size changes.  As I said, this only happens once.

**Comment by Thumbkin** [comment] 2021-06-09 09:27
"Many errors related to the "CompactRaidFrame" frames are errors caused by taint of other addons (and it’s very difficult to know which one is really), and then in the Lua error message the name of any other addon may appear."

This is what I found on the internet. It seems the BugGrabber just random picks the name of an addon, but it is not necessarily the name of the addon that is causing it. 

IF you can disable all other but MTSL addons and see if the error pops up again, I am pretty sure it wont, so this will be cause by any other addon. Do you use any addons manipulating untiframes? Then my best bet would be that that addon is causing the errors

**Comment by rbpaiett** [comment] 2021-06-09 12:11
Well as I said, I had my doubts it was actually your addon because it's unrelated. I didn't know what you told me can happen with the game reporting errors.

**Comment by Thumbkin** [comment] 2021-06-10 10:19
Going to close this for now.

**Closed by Thumbkin** 2021-06-10 10:20 UTC
